### ISSUE TITLE
Donation portal / Auto update not working

### ISSUE THREAD

**Issue by Whaylee** [pupnewfster/GalaxyGamingIssues#1]
The donation command !donation bring your to an empty donation like. And after donating the server prom doesn't auto update the users donor points.

I have already given the two players who donated their points.

**Comment by EGScorpion** [comment]
[Prometheus repeated error of 23:09:11 - 01/06/2017] Neither MySQLoo or tmysql4 module could be loaded! Please go to  http://wiki.prometheusipn.com/index.php?title=Installation:lua_prerequisites  and follow the instructions on how to install MySQLoo or tmysql4!

I found that in the console of the TTMC.

**Comment by ghost** [comment]
This is also still an issue :(

**Comment by ghost** [comment]
Mysqloo error
