### ISSUE TITLE
Knife slot/Crowbar issue

### ISSUE THREAD

**Issue by EGScorpion** [pupnewfster/GalaxyGamingIssues#10]
After equipping the knife it gets rid of the crowbar like its supposed to but the crowbar comes back when the round starts.

**Comment by ghost** [comment]
I mean, i don't know if this is a "bug", it'd be nice to still have the crowbar too, since you can push, but the knife also will break blocks i believe?

**Comment by ghost** [comment]
Should be in the gamemode. I will double check those lua files and add a hook for it.

**Comment by ghost** [comment]
Not too sure if this is still an issue?
Personally I've never lost my crowbar.

**Comment by ghost** [comment]
Could we possibly just change the knife slot for that?

On Fri, Jul 28, 2017 at 12:00 PM, Sabrina Stafford <notifications@github.com

**Comment by ghost** [comment]
We made it one, seeing as Traitor/Detective menu, if you buy stuff, it takes that slots besides 1. And when we had the knife before as slot 7, restricted stuff and stated there's something already taken in that slot

**Comment by ghost** [comment]
Those menus should only populate slots 7 and 8, with few exceptions if any.
What is in slot 6?

On Fri, Jul 28, 2017 at 12:51 PM, Sabrina Stafford <notifications@github.com

**Comment by ghost** [comment]
Hm, surprisingly, the only slot open. Must have missed that.

**Comment by ghost** [comment]
Since Slot 6 is holstered

**Comment by ghost** [comment]
If 6 is holstered then it's not open, wym

**Comment by ghost** [comment]
I mean, it's the only slot you can't pick up / buy for. It's set as holstered. So really our options are 1 or 6.

**Comment by ghost** [comment]
Is it limited to the amount of slots? Was on a diff server, and they had the knife in slot 12?
Also I don't think this is even an issue??

**Comment by ghost** [comment]
This hasn't happened since we first added.
