### ISSUE TITLE
Too Many Indices for Index Buffer

### ISSUE THREAD

**Issue by ghost** [pupnewfster/GalaxyGamingIssues#11]
Tell a programmer (37108 > 32768)

Happened on City and B5

**Comment by pupnewfster** [comment]
I believe this is fixed, now that we have disabled some of the super high def player models. If this is not reopen this issue.

**Comment by ghost** [comment]
Next time it happens, see if you can find a stacktrace for the error in your console.

**Comment by pupnewfster** [comment]
I wonder if this has anything to do with, http://store.steampowered.com/news/externalpost/pcgamer/2079952210084838828

**Comment by ghost** [comment]
Seems to be fixed.

**Comment by ghost** [comment]
Seems to be when using the pump shotgun?
Happened twice in a row when I was shooting innocents.

"[T-Mod]Dirty Dans: like when a bullet hits a corner and there's no hitbox for it, the server can't register it there and it crashes trying to figure it out"
