### ISSUE TITLE
Acrashscreen

### ISSUE THREAD

**Issue by ghost** [pupnewfster/GalaxyGamingIssues#12]
Not sure if we should just take it off or find out how to fix.  Since we don't have an nfo server to replace the link.
` This should point to file 'status-update.php'

__config__.updateStatusURL = "http://exoticgaming.site.nfoservers.com/acrashscreen/status/status-update.php"
`

**Comment by pupnewfster** [comment]
Having an nfo server is irrelevant as it is just a webpage. You can use http://galaxygaming.gg/tttmc/status-update.php by putting a file called status-update.php in the tttmc folder in the ftp. Make sure the file has the needed information inside of it. (I am unsure what information is needed)

**Comment by ghost** [comment]
So it doesn't matter that the site goes nowhere? and why would I have a second file in the fast dl?

**Comment by pupnewfster** [comment]
no I am saying, that you can make the page that it goes to. And the fast dl is in the tttmc/fastdl folder, but how it is set up we can also use that tttmc folder for pages we need.

**Comment by ghost** [comment]
Fixed.
