### ISSUE TITLE
ZS Pointshop & Models

### ISSUE THREAD

**Issue by ghost** [pupnewfster/GalaxyGamingIssues#17]
# Description

- [ ] Make model selection through ps2
- [ ] Disable model selection from F1 menu
- [ ] Add hint telling players to use !shop

## Server, select all that apply

- [ ] TTT MC
- [ ] Prop Hunt
- [x] Zombie Survival
- [ ] DarkRP
- [ ] TeamSpeak
- [ ] Website
- [ ] RSPS
- [ ] Other please specify:

**Comment by pupnewfster** [comment]
ZS is no more.
