### ISSUE TITLE
DarkRP Hitman and Bank Guard Models

### ISSUE THREAD

**Issue by crispytaco2** [pupnewfster/GalaxyGamingIssues#21]
# Description

DJ need to be updated. Cinema mods need update. Bank guard and Hitman PM need update. If i can find or think of anymore issues i will let you know thank you

## Server, select all that apply

- [ ] TTT MC
- [ ] Prop Hunt
- [ ] Zombie Survival
- [x] DarkRP
- [ ] TeamSpeak
- [ ] Website
- [ ] RSPS
- [ ] Other please specify:

**Comment by ghost** [comment]
Only issue remaining is those two jobs need models.

**Comment by ghost** [comment]
Fixed.
