### ISSUE TITLE
DarkRP Errors

### ISSUE THREAD

**Issue by MrPlaylist** [pupnewfster/GalaxyGamingIssues#23]
# Description
Ya'll broke it, ya'll fix it. 
[ERROR] A runtime error has occurred in "addons/rprint/lua/rprint/sh_rprint.lua" on line 183.
The best help I can give you is this:

The category of "Bronze Printer" ("Printers") does not exist!

Hints:
 - Make sure the category is created with DarkRP.createCategory.
 - The category name is case sensitive!
 - Categories must be created before DarkRP finished loading.

The responsibility for the error above lies with (the authors of) one (or more) of these files:
 1. addons/rprint/lua/rprint/sh_rprint.lua on line 183
 2. addons/rprint/lua/rprint/sh_config.lua on line 121
 3. function 'include'
 4. addons/rprint/lua/autorun/sh_rprint_load.lua on line 5
 5. addons/rprint/lua/autorun/sh_rprint_load.lua on line 19
 6. addons/ulib-v2_61/lua/ulib/shared/hook.lua on line 110
------- End of Simplerr error -------

There is 1 Lua problem!
 Please check your console for more information!
[ERROR] A runtime error has occurred in "addons/rprint/lua/rprint/sh_rprint.lua" on line 183.
The best help I can give you is this:

The category of "Silver Printer" ("Printers") does not exist!

Hints:
 - Make sure the category is created with DarkRP.createCategory.
 - The category name is case sensitive!
 - Categories must be created before DarkRP finished loading.

The responsibility for the error above lies with (the authors of) one (or more) of these files:
 1. addons/rprint/lua/rprint/sh_rprint.lua on line 183
 2. addons/rprint/lua/rprint/sh_config.lua on line 140
 3. function 'include'
 4. addons/rprint/lua/autorun/sh_rprint_load.lua on line 5
 5. addons/rprint/lua/autorun/sh_rprint_load.lua on line 19
 6. addons/ulib-v2_61/lua/ulib/shared/hook.lua on line 110
------- End of Simplerr error -------

There is 1 Lua problem!
 Please check your console for more information!
[ERROR] A runtime error has occurred in "addons/rprint/lua/rprint/sh_rprint.lua" on line 183.
The best help I can give you is this:

The category of "Gold Printer" ("Printers") does not exist!

Hints:
 - Make sure the category is created with DarkRP.createCategory.
 - The category name is case sensitive!
 - Categories must be created before DarkRP finished loading.

The responsibility for the error above lies with (the authors of) one (or more) of these files:
 1. addons/rprint/lua/rprint/sh_rprint.lua on line 183
 2. addons/rprint/lua/rprint/sh_config.lua on line 159
 3. function 'include'
 4. addons/rprint/lua/autorun/sh_rprint_load.lua on line 5
 5. addons/rprint/lua/autorun/sh_rprint_load.lua on line 19
 6. addons/ulib-v2_61/lua/ulib/shared/hook.lua on line 110
------- End of Simplerr error -------

There is 1 Lua problem!
 Please check your console for more information!
[ERROR] A runtime error has occurred in "addons/rprint/lua/rprint/sh_rprint.lua" on line 183.
The best help I can give you is this:

The category of "Platinum Printer" ("Printers") does not exist!

Hints:
 - Make sure the category is created with DarkRP.createCategory.
 - The category name is case sensitive!
 - Categories must be created before DarkRP finished loading.

The responsibility for the error above lies with (the authors of) one (or more) of these files:
 1. addons/rprint/lua/rprint/sh_rprint.lua on line 183
 2. addons/rprint/lua/rprint/sh_config.lua on line 177
 3. function 'include'
 4. addons/rprint/lua/autorun/sh_rprint_load.lua on line 5
 5. addons/rprint/lua/autorun/sh_rprint_load.lua on line 19
 6. addons/ulib-v2_61/lua/ulib/shared/hook.lua on line 110
------- End of Simplerr error -------

There is 1 Lua problem!
 Please check your console for more information!
[ERROR] A runtime error has occurred in "addons/rprint/lua/rprint/sh_rprint.lua" on line 183.
The best help I can give you is this:

The category of "Diamond Printer" ("Printers") does not exist!

Hints:
 - Make sure the category is created with DarkRP.createCategory.
 - The category name is case sensitive!
 - Categories must be created before DarkRP finished loading.

The responsibility for the error above lies with (the authors of) one (or more) of these files:
 1. addons/rprint/lua/rprint/sh_rprint.lua on line 183
 2. addons/rprint/lua/rprint/sh_config.lua on line 195
 3. function 'include'
 4. addons/rprint/lua/autorun/sh_rprint_load.lua on line 5
 5. addons/rprint/lua/autorun/sh_rprint_load.lua on line 19
 6. addons/ulib-v2_61/lua/ulib/shared/hook.lua on line 110
------- End of Simplerr error -------

## Server, select all that apply

- [ ] TTT MC
- [ ] Prop Hunt
- [ ] Zombie Survival
- [x] DarkRP
- [ ] TeamSpeak
- [ ] Website
- [ ] RSPS
- [ ] Other please specify:

**Comment by ghost** [comment]
Seems to be fixed. Thanks scorp.
