### ISSUE TITLE
IGNORE THIS AND DELETE IT PLEASE

### ISSUE THREAD

**Issue by crispytaco2** [pupnewfster/GalaxyGamingIssues#30]
They're fucked

Alot of the cars in the TDM pack are just fucked up and probably need to be updated, Same with SGM cars.
all LW cars are fine though

List of cars packs that are messed up: TDM Pack, SGM Pack, ST cars Pack, TDM emergency Pack

List of car packs that are fine: SenCo Pack, Both LW Packs, and Emergency car Pack is fine.

## Server, select all that apply

- [ ] TTT MC
- [ ] Prop Hunt
- [ ] Zombie Survival
- [x] DarkRP
- [ ] TeamSpeak
- [ ] Website
- [ ] RSPS
- [ ] Other please specify:

**Comment by EGScorpion** [comment]
What does "fucked up" mean what is the actual issue?
