### ISSUE TITLE
Blocking Banned Spots

### ISSUE THREAD

**Issue by Insane-Leader** [pupnewfster/GalaxyGamingIssues#33]
# Description

Is There anyway to get in touch with map makers for we can edit the maps and getting banned spots blocked for people don't use them anymore

## Server, select all that apply

- [ ] TTT MC
- [X] Prop Hunt
- [ ] Zombie Survival
- [ ] DarkRP
- [ ] TeamSpeak
- [ ] Website
- [ ] RSPS
- [ ] Other please specify:

**Comment by Harsh-man** [comment]
Can Rootbeer do this? If not, I can mess around with the map editor he uses, see if I can.

**Comment by ghost** [comment]
Not sure this is an issue anymore.
