### ISSUE TITLE
Daily Reward System for Staff

### ISSUE THREAD

**Issue by ghost** [pupnewfster/GalaxyGamingIssues#34]
# Description

### Active in 
To be qualified for this, an hour and a half is required on your designated server.

### Somewhat active in : 
- Teamspeak
- Discord
- Forums

### **Tiered Reward**
1 Day - 200 donor points
2 Day - 300 donor points
3 Day - 400 donor points
and so forth

2 weeks straight potentially rewarded a personal player model or custom weapon only to them.

## Server, select all that apply

- [x] TTT MC
- [x] Prop Hunt
- [x] Zombie Survival
- [x] DarkRP
- [ ] TeamSpeak
- [ ] Website
- [ ] RSPS
- [ ] Other please specify:

**Comment by ghost** [comment]
Not sure if we could make this for the staff only? https://www.gmodstore.com/scripts/view/3457/daily-rewards-pointshop-2

**Comment by ghost** [comment]
Could Use everyones opinions for rewards
Would be nice to have different inputs since it'll vary for each server

**Comment by EGScorpion** [comment]
Don't think we'd need to spend money on that we did it just fine on the forums awhile ago.

**Comment by ghost** [comment]
Well that was weekly how we did it. This would potentially be automatic and would be for everyone doing it. Not just one person ya know?

**Comment by ghost** [comment]
Welp. Imma just do this for TTT since ph is dead.

### Must be active
- At least an hour a day
- Semi Active in Teamspeak / Discord / Slack

## Rewards Given Weekly
**May choose one listed:**
- 500 Donor Points
- 10,000 Points
- Personal Player Model

Whoever is selected:
- Featured in game chat "Congrats to "Username" for being our most active staff!"
