### ISSUE TITLE
Loading Screen Music and Map Change every few weeks

### ISSUE THREAD

**Issue by Insane-Leader** [pupnewfster/GalaxyGamingIssues#37]
# Description

Can we look into changing the loading screen music and maps every few weeks to keep everything interesting.

## Server, select all that apply

- [x] TTT MC
- [X] Prop Hunt
- [x] Zombie Survival
- [ ] DarkRP
- [ ] TeamSpeak
- [ ] Website
- [ ] RSPS
- [ ] Other please specify:

**Comment by ghost** [comment]
Adding a calendar to help with this https://galaxygaming.slack.com/services/gcalendar

**Comment by ghost** [comment]
Ill create a playlist of music to choose from. The day before please message(assuming me unless you got ph staff ftp)to update the loading screen.
