### ISSUE TITLE
Solution to Team Switching Problem

### ISSUE THREAD

**Issue by ashypashyxoxo** [pupnewfster/GalaxyGamingIssues#42]
# Description

many people are constantly switching which is causing uneven teams. Maybe place in an automated system for it?

## Server, select all that apply

- [ ] TTT MC
- [X] Prop Hunt
- [ ] Zombie Survival
- [ ] DarkRP
- [ ] TeamSpeak
- [ ] Website
- [ ] RSPS
- [ ] Other please specify:

**Comment by EGScorpion** [comment]
Eh something for chief to do in his free time I still do this day can't figure out how exo made his force team switch let alone figure out how to make it automatic
