### ISSUE TITLE
ttt_mc_seriouscraft Map Issue

### ISSUE THREAD

**Issue by Niitr0gen** [pupnewfster/GalaxyGamingIssues#43]
# Description

While playing the ttt_mc_seriouscraft map, we had no end of round box pop up when the Traitors or Innocents are killed.  Map also didn't give the map vote automatically after 10 rounds.  When the map was changed (I made a manual vote and forced a map change), all of the mentioned menus above were fully functioning.  This could be fixed with the server reset that is coming in the future, but I'm no genius when it comes to that kind of stuff.

Forgot to mention this yesterday during the meeting.

## Server, select all that apply

- [x] TTT MC
- [ ] Prop Hunt
- [ ] Zombie Survival
- [ ] DarkRP
- [ ] TeamSpeak
- [ ] Website
- [ ] RSPS
- [ ] Other please specify:

**Comment by ghost** [comment]
Removing map for now.
