### ISSUE TITLE
Getting rid of the infinite taunt from taunt menu

### ISSUE THREAD

**Issue by Insane-Leader** [pupnewfster/GalaxyGamingIssues#44]
# Description

Can we get rid of the infinite taunt (running in the 90's) from the taunt menu it's being used to ghost now because when someone plays it and when they die it follows them when dead so they lead them to the living props

## Server, select all that apply

- [ ] TTT MC
- [X] Prop Hunt
- [ ] Zombie Survival
- [ ] DarkRP
- [ ] TeamSpeak
- [ ] Website
- [ ] RSPS
- [ ] Other please specify:

**Comment by EGScorpion** [comment]
Done
