### ISSUE TITLE
Prop Hunt Loading Screen 

### ISSUE THREAD

**Issue by ghost** [pupnewfster/GalaxyGamingIssues#45]
## The Playlist of Available Songs
- [ ] City Lights - Just In Case
- [ ] The Neighborhood - Daddy Issues
- [x] Fit for Rivals - Damage
- [ ] Downplay - The One Who Laughs Last
- [x] Hollywood Undead - I Don't Wanna Die
- [ ] Imagine Dragons - Whatever It Takes
- [x] Ivy Levan - Biscuit
- [x] Killswitch Engage - The Arms of Sorrow
- [ ] Manafest - Impossible ft. Trevor McNevan
- [x] Out For Tomorrow - Give Me A Reason
- [ ] Palisades - The Reckoning ft. Chris Roetter
- [ ] Phantom Sage - Our Lives Past ft. Emily Stiles
- [ ] Palisades - Happy
- [ ] Skillet - Back From The Dead
- [ ] Skillet - Burn It Down
- [ ] Starset - Monster
- [ ] Vicetone - United We Dance
- [ ] Warsongs - Piercing Light
- [ ] We As Human - Strike Back
- [ ] We As Human - Take The Bullets Away ft. Lacey Sturm

## Things To Comment Below

- 3-5 songs every 2 weeks 
*Will check ones already done until full cycle*

- Any updates to News box

**Comment by Insane-Leader** [comment]
Killswitch Engage - Arms of Sorrow
Ive Levan - Kiss My Biscuit
Hollywood Undead - I Don't Wanna Die
Fit For Rivals - Damage
Out For Tomorrow - Give Me A Reason

**Comment by pupnewfster** [comment]
As there is no loading music I am closing this.
