### ISSUE TITLE
Remove 90s Taunt

### ISSUE THREAD

**Issue by ghost** [pupnewfster/GalaxyGamingIssues#46]
# Description

Still able to be picked.

## Server, select all that apply

- [ ] TTT MC
- [x] Prop Hunt
- [ ] Zombie Survival
- [ ] DarkRP
- [ ] TeamSpeak
- [ ] Website
- [ ] RSPS
- [ ] Other please specify:

**Comment by EGScorpion** [comment]
I thought I did... I'll look at it again

**Comment by Harsh-man** [comment]
Why does it have to be removed? 90's is my favorite. ;-;

**Comment by ghost** [comment]
Because it was being abused.
