### ISSUE TITLE
Loading Screen Error

### ISSUE THREAD

**Issue by Harsh-man** [pupnewfster/GalaxyGamingIssues#50]
# Description

On the ZS loading screen, the song "Back from the dead" by Skillet does not play any audio. All the other songs do.

## Server, select all that apply

- [ ] TTT MC
- [ ] Prop Hunt
- [x] Zombie Survival
- [ ] DarkRP
- [ ] TeamSpeak
- [ ] Website
- [ ] RSPS
- [ ] Other please specify:

**Comment by ghost** [comment]
Uhh I don't have access for some reason so someone else will have to either gimmie access or fix it lol

**Comment by EGScorpion** [comment]
I'll fix it.

**Comment by ghost** [comment]
Is this fixed yet?
