### ISSUE TITLE
Loading screen suggestion / ttt

### ISSUE THREAD

**Issue by Jonboy2k** [pupnewfster/GalaxyGamingIssues#51]
# Description

You should have map specific rules on the loading screen corresponding to the current map

## Server, select all that apply

- [x] TTT MC
- [ ] Prop Hunt
- [ ] Zombie Survival
- [ ] DarkRP
- [ ] TeamSpeak
- [ ] Website
- [ ] RSPS
- [ ] Other please specify:

**Comment by ghost** [comment]
Seeing as most current maps do not have specific rules, I'm closing this :D
