### ISSUE TITLE
Grillby & Viper skin's are broken

### ISSUE THREAD

**Issue by Jonboy2k** [pupnewfster/GalaxyGamingIssues#52]
# Description

Having testing these two skins with Mr. Playlist, we both concluded that the head hitbox on the two skins are broken, as getting shot in the head with a rifle does not kill them.

## Server, select all that apply

- [x] TTT MC
- [ ] Prop Hunt
- [ ] Zombie Survival
- [ ] DarkRP
- [ ] TeamSpeak
- [ ] Website
- [ ] RSPS
- [ ] Other please specify:

**Comment by Jonboy2k** [comment]
Forgot to add that the T's silenced sniper doesn't one shot head shot.

**Comment by ghost** [comment]
So are you wanting these two player models to be taken out?

**Comment by Jonboy2k** [comment]
Unless someone knows how to fix the hitboxes, yes. I feel like it'll be good to remove.

**Comment by ghost** [comment]
All broken ones were removed.
