### ISSUE TITLE
Custom Mapvote

### ISSUE THREAD

**Issue by Exo2986** [pupnewfster/GalaxyGamingIssues#54]
# Description

Yes

## Server, select all that apply

- [x] TTT MC
- [ ] Prop Hunt
- [ ] Zombie Survival
- [ ] DarkRP
- [ ] TeamSpeak
- [ ] Website
- [ ] RSPS
- [ ] Other please specify:

**Comment by pupnewfster** [comment]
https://github.com/pupnewfster/TTTMC/commit/6dfe3b509108d35258f83378a0f0fc16b9e8765f
