### ISSUE TITLE
New Maps Needed for Prop Hunt

### ISSUE THREAD

**Issue by Insane-Leader** [pupnewfster/GalaxyGamingIssues#57]
Prop Hunt could definitely use some new maps since people are complaining of it being stale and boring due to lack of maps this isn't a huge priority but might be an easy thing to get done to get people on Prop Hunt and to get them to stop complaining as much 

## Server, select all that apply

- [ ] TTT MC
- [X] Prop Hunt
- [ ] TeamSpeak
- [ ] Website
- [ ] Discord
- [ ] Slack
- [ ] Other please specify:

**Comment by PuNcAk3** [comment]
Any map ideas you're thinking about?

**Comment by ghost** [comment]
Map Additions:

- Ph_youturd
- Ph_warehouse
- Ph_GalaxyGamingAcademy  (removed for now, wrong map in addon)
- ph_backyard
