### ISSUE TITLE
Map Vote for Prop Hunt

### ISSUE THREAD

**Issue by pupnewfster** [pupnewfster/GalaxyGamingIssues#58]
# Description

Port our custom map vote to Prop Hunt, and then with the images of each map add them to the Prop Hunt loading screen to make it look better.

## Server, select all that apply

- [ ] TTT MC
- [x] Prop Hunt
- [ ] TeamSpeak
- [ ] Website
- [ ] Discord
- [ ] Slack
- [ ] Other please specify:

**Comment by Exo2986** [comment]
Done and implemented, will be added with PH Major Update #1.
