### ISSUE TITLE
Map issues in prophunt

### ISSUE THREAD

**Issue by BobAgentofHydra** [pupnewfster/GalaxyGamingIssues#59]
# Description

The backyard map doesn't load in and Warehouse has a fence where you can get out of the map easily so it should probably be removed for now. 

## Server, select all that apply

- [ ] TTT MC
- [x] Prop Hunt
- [ ] TeamSpeak
- [ ] Website
- [ ] Discord
- [ ] Slack
- [ ] Other please specify:

**Comment by ghost** [comment]
Will remove Backyard tomorrow night. 

Warehouse I believe is fine, seeing as you explained how the only way you can get up there is with other props and so forth.

The two maps Reshiram suggested, Lockup and Starship, both that have been on the server, will be re-added Tuesday.
