### ISSUE TITLE
Mods can't see list friends on Prophunt

### ISSUE THREAD

**Issue by BobAgentofHydra** [pupnewfster/GalaxyGamingIssues#60]
# Description

The mods have the ability to list friends of people but because it is a silent message they can't actually _see_ who the friends are. Which makes it so they can't really help prove that people are ghosting. It would be nice if they can see that specific silent message.

## Server, select all that apply

- [ ] TTT MC
- [x] Prop Hunt
- [ ] TeamSpeak
- [ ] Website
- [ ] Discord
- [ ] Slack
- [ ] Other please specify:

**Comment by ghost** [comment]
In the process of letting Mod+ see the silent command for Listfriends

**Comment by Exo2986** [comment]
Fixed, issue closed.
