### ISSUE TITLE
Mute Menu 

### ISSUE THREAD

**Issue by ghost** [pupnewfster/GalaxyGamingIssues#61]
# Description

To let players mute/unmute.

**http://wiki.garrysmod.com/page/Player/SetMuted**
## Server, select all that apply

- [ ] TTT MC
- [x] Prop Hunt
- [ ] TeamSpeak
- [ ] Website
- [ ] Discord
- [ ] Slack
- [ ] Other please specify:

**Comment by Harsh-man** [comment]
Are you looking for an addon for this, or something else?

**Comment by ghost** [comment]
Na he's gonna write something and make a command. Way easier.

**Comment by Exo2986** [comment]
Already have, waiting to test and implement.

**Comment by ghost** [comment]
To use,  simply do !localmute and !unlocalmute.
