### ISSUE TITLE
New Player Models for Prop Hunt and removal of unused ones

### ISSUE THREAD

**Issue by BobAgentofHydra** [pupnewfster/GalaxyGamingIssues#62]
# Description

- [x] Joker
https://steamcommunity.com/sharedfiles/filedetails/?id=400762901
- [x] Master Chief
https://steamcommunity.com/sharedfiles/filedetails/?id=139247091
- [x] Miku
http://steamcommunity.com/sharedfiles/filedetails/?id=854634173&searchtext=miku
- [x] Daredevil
http://steamcommunity.com/sharedfiles/filedetails/?id=655371599
- [x] Spider man
http://steamcommunity.com/sharedfiles/filedetails/?id=973656364
- [x] Venom
http://steamcommunity.com/sharedfiles/filedetails/?id=517412134
- [x] Star Lord
http://steamcommunity.com/sharedfiles/filedetails/?id=497718395
- [x] Rocket Raccoon
http://steamcommunity.com/sharedfiles/filedetails/?id=654384195
- [x] Rick
http://steamcommunity.com/sharedfiles/filedetails/?id=557711922
- [x] Morty
http://steamcommunity.com/sharedfiles/filedetails/?id=706896834

Premium (Donor)
- [x] Kirito
https://steamcommunity.com/sharedfiles/filedetails/?id=702836882&searchtext=
- [x] Carnage
http://steamcommunity.com/sharedfiles/filedetails/?id=472748256
- [x] Tiny Tina
https://steamcommunity.com/sharedfiles/filedetails/?id=378054846
- [x] Mr Poopybutthole
http://steamcommunity.com/sharedfiles/filedetails/?id=727666020

**Remove:**

- [x] Kamshak
- [x] Griim
- [x] Phoenix
- [x] Niandra
- [x] Ruben
- [x] Joker
- [x] Knight
- [x] Midna
- [x] Adam
- [x] Rorschach

- [x]  **Make Superman, Flash, Green Lantern and Batman 3,600 Points**

## Server, select all that apply

- [ ] TTT MC
- [x] Prop Hunt
- [ ] TeamSpeak
- [ ] Website
- [ ] Discord
- [ ] Slack
- [ ] Other please specify:

**Comment by ghost** [comment]
# Maps # 

- [x] ph_awesomebuilding
- [x] ph_bank
- [x] ph_lockup
- [x] ph_marketbattle
- [x] ph_starship

**Comment by ghost** [comment]
All player models have been removed, added, and changed.
Maps are on as well.

The player models will be in a category labeled **NEW Playmodels** under _Not for Sale_ so you can put prices as you like.
