### ISSUE TITLE
Boxes around player labels in PH scoreboard

### ISSUE THREAD

**Issue by Exo2986** [pupnewfster/GalaxyGamingIssues#65]
# Description

https://i.gyazo.com/a85c238a37fdfbf7e8c2a8dd87e9ff0e.png

is big gay and should be fixed is v ez

## Server, select all that apply

- [ ] TTT MC
- [x] Prop Hunt
- [ ] TeamSpeak
- [ ] Website
- [ ] Discord
- [ ] Slack
- [ ] Other please specify:

**Comment by pupnewfster** [comment]
No longer an issue with the new scoreboard.
