### ISSUE TITLE
Prop Hunt FastDL

### ISSUE THREAD

**Issue by pupnewfster** [pupnewfster/GalaxyGamingIssues#67]
# Description

Add the Prop Hunt maps to FastDL. This would likely give a minor speed up in load time for Prop Hunt.

## Server, select all that apply

- [ ] TTT MC
- [x] Prop Hunt
- [ ] TeamSpeak
- [ ] Website
- [ ] Discord
- [ ] Other please specify:

**Comment by ghost** [comment]
Signed, sealed, and delivered.
