### ISSUE TITLE
New scoreboard materials need to be added to the FastDL

### ISSUE THREAD

**Issue by Exo2986** [pupnewfster/GalaxyGamingIssues#69]
# Description

ur granny tranny

## Server, select all that apply

- [x] TTT MC
- [x] Prop Hunt
- [ ] TeamSpeak
- [ ] Website
- [ ] Discord
- [ ] Other please specify:

**Comment by ghost** [comment]
Also making the scoreboard not block mapvote.

**Comment by Exo2986** [comment]
yes is ez fix

**Comment by ghost** [comment]
ur mom was an ez fix

**Comment by Exo2986** [comment]
heck

**Comment by Exo2986** [comment]
done
