### ISSUE TITLE
Stuff to add in TTT

### ISSUE THREAD

**Issue by SkellyJames** [pupnewfster/GalaxyGamingIssues#78]
# Description
Add the stuff in the docs please
https://docs.google.com/document/d/18VgFzoy9EFi6EDMj1ckRkDSyXe-kBkmmMeogzub1UiQ/edit?usp=sharing

## Server, select all that apply

- [ ] Prop Hunt
- [ ] AutismRP
- [x] TTT
- [ ] TeamSpeak
- [ ] Website
- [ ] Discord
- [ ] Other please specify:

**Comment by pupnewfster** [comment]
Added
