### ISSUE TITLE
Stuff to do in TTT

### ISSUE THREAD

**Issue by SkellyJames** [pupnewfster/GalaxyGamingIssues#81]
# Description
1. I would like to have a list of every addons on the TTT server (with a google doc if possible with
    links(optional) )
2. The knife is taking two hits before killing instead of the one hit kill.
3. Remove the map Mc village
4. demotes the mods of TTT cause they are doing nothing and aren't even going on TTT

## Server, select all that apply

- [ ] Prop Hunt
- [ ] AutismRP
- [x] TTT
- [ ] TeamSpeak
- [ ] Website
- [ ] Discord
- [ ] Other please specify:

**Comment by pupnewfster** [comment]
1. No
2. Done
3. Done
4. You can do it yourself
5. Don't group up a bunch of random issues that don't have to do with each other into one issue.
